// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAfrx9IZzJcZy1IB9YoTYhsQWJfZ3LSsg',
    appId: '1:682888162313:web:1ad576fe0a598a0b9e9cd8',
    messagingSenderId: '682888162313',
    projectId: 'task-app-464f1',
    authDomain: 'task-app-464f1.firebaseapp.com',
    storageBucket: 'task-app-464f1.firebasestorage.app',
    measurementId: 'G-SR4T0DDT24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgaIcr1xGYyCosSGrp2pJ1jO7Mpiey08',
    appId: '1:682888162313:android:2d1697b373d6d76f9e9cd8',
    messagingSenderId: '682888162313',
    projectId: 'task-app-464f1',
    storageBucket: 'task-app-464f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGu5juSwpOFG2jP5JGs7A4Upg1Hm-rrJE',
    appId: '1:682888162313:ios:9b28e4fca1c9dc979e9cd8',
    messagingSenderId: '682888162313',
    projectId: 'task-app-464f1',
    storageBucket: 'task-app-464f1.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGu5juSwpOFG2jP5JGs7A4Upg1Hm-rrJE',
    appId: '1:682888162313:ios:9b28e4fca1c9dc979e9cd8',
    messagingSenderId: '682888162313',
    projectId: 'task-app-464f1',
    storageBucket: 'task-app-464f1.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAfrx9IZzJcZy1IB9YoTYhsQWJfZ3LSsg',
    appId: '1:682888162313:web:6743deb2d6c83f7f9e9cd8',
    messagingSenderId: '682888162313',
    projectId: 'task-app-464f1',
    authDomain: 'task-app-464f1.firebaseapp.com',
    storageBucket: 'task-app-464f1.firebasestorage.app',
    measurementId: 'G-3C72BXKY3B',
  );
}
